-- Table: public.state
 
-- DROP TABLE IF EXISTS public.state;
 
CREATE TABLE IF NOT EXISTS public.state
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    country_id bigint NOT NULL,
    CONSTRAINT state_pkey PRIMARY KEY (id),
    CONSTRAINT fkghic7mqjt6qb9vq7up7awu0er FOREIGN KEY (country_id)
        REFERENCES public.country (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
 
TABLESPACE pg_default;
 
ALTER TABLE IF EXISTS public.state
    OWNER to postgres;