-- Table: public.city
 
-- DROP TABLE IF EXISTS public.city;
 
CREATE TABLE IF NOT EXISTS public.city
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    state_id bigint NOT NULL,
    CONSTRAINT city_pkey PRIMARY KEY (id),
    CONSTRAINT fkghic7mqjt6qb9vq7up7awu0er FOREIGN KEY (state_id)
        REFERENCES public.state (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
 
TABLESPACE pg_default;
 
ALTER TABLE IF EXISTS public.city
    OWNER to postgres;