-- Table: public.bank_service

-- DROP TABLE IF EXISTS public.bank_service;

CREATE TABLE IF NOT EXISTS public.bank_service
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    card_id bigint,
    CONSTRAINT bank_service_pkey PRIMARY KEY (id),
    CONSTRAINT fk237c91ls7icmfan2q26nj1o9x FOREIGN KEY (card_id)
        REFERENCES public.card (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.bank_service
    OWNER to postgres;
