-- Table: public.card

-- DROP TABLE IF EXISTS public.card;

CREATE TABLE IF NOT EXISTS public.card
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    account_id bigint,
    daily_limit integer,
    monthly_limit integer,
    CONSTRAINT card_pkey PRIMARY KEY (id),
    CONSTRAINT fk8v67eys6tqflsm6hrdgru2phu FOREIGN KEY (account_id)
        REFERENCES public.account (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.card
    OWNER to postgres;